---
##############################################################################
#
# Version tag: 0.4.2
#
##############################################################################
- name: "Apply Shared playbook configuration"
  hosts:
  - "{{ include_hosts | default('all') }}"
  - "!proxmox_hosts"
#  - "!pi_exclude_hosts"
#  - "!pi_hosts"
#  - "!lab"
  #gather_facts: true
  order: sorted
  tags:
    - shared
  collections:
    - ansible.posix
    - community.general
    - kubernetes.core

  roles:
    #######################
    # Connectivity checks #
    #######################
    - { role: check_connectivity, CHECK_CONNECTIVITY_port: 53, CHECK_CONNECTIVITY_host: "{{ NAMED_ns1 }}",                            tags: check_dns }
    - { role: check_connectivity, CHECK_CONNECTIVITY_port: 53, CHECK_CONNECTIVITY_host: "{{ NAMED_ns2 }}",                            tags: check_dns }
    - { role: check_connectivity, CHECK_CONNECTIVITY_port: 53, CHECK_CONNECTIVITY_host: "{{ NAMED_ns3 }}",                            tags: check_dns }

    #################
    # Configuration #
    #################
#    - { role: os_role,          tags: os_role }
#    - { role: repos,            tags: repos }
#    - { role: packages,         tags: packages }
#    - { role: rhel,             tags: rhel,               when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 9 }
    - { role: accounting,       tags: accounting }
#    - { role: rootpw,           tags: rootpw }
#    - { role: ansible_user,     tags: ansible_user }
    - { role: authorized_keys,  tags: authorized_keys }
#    - { role: netplan,          tags: netplan,            when: ansible_distribution == 'Ubuntu' }
#    - { role: rh_network,       tags: networkmanager,     when: not ansible_distribution == 'Ubuntu' }
    - { role: motd,             tags: motd }
#    - { role: zsh,              tags: zsh }
#    - { role: zabbix_agent2,    tags: zabbix_agent2 }
    - { role: duo_unix,         tags: duo_unix,           when: not ( ( duounix_secret_key is undefined ) or
                                                                ( duounix_secret_key is none ) or
                                                                ( duounix_secret_key | trim == '') ) }
#    - { role: root_files,       tags: root_files }
    - { role: glusterfs,        tags: glusterfs,          when: inventory_hostname in groups.gluster_hosts and ansible_os_family == "RedHat" }
