# Prometheus Configuration File

global:
  scrape_interval: 15s  # How often to scrape targets by default.
  evaluation_interval: 15s  # How often to evaluate rules.

# Alerting rules
# Replace this path with the location of your alerting rules file.
rule_files:
  - '/alerting_rules.yml'

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Example job for monitoring a node_exporter instance
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  # Scrape cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:9900']

  # Scrape targets via Blackbox Exporter
  # This job uses the Blackbox Exporter to probe specified targets for availability and HTTP status.
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Use the built-in module to check for HTTP 200 responses.
    static_configs:
      - targets:
          - http://prometheus.io    # Target to probe with http.
          - https://prometheus.io   # Target to probe with https.
          - http://example.com:8080 # Target to probe with http on port 8080.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # Blackbox Exporter hostname:port.

# Optional Alertmanager configuration (uncomment if needed)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - 'localhost:9093'  
